### ISSUE TITLE
warning "Wide character in print" when regex contains UTF-8 chars

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-App-RegexpPatternUtils#1]
The command-line tools wrongly assume that output contains only ASCII characters.

Recent releases of Regexp::Pattern::License adds some non-ASCII chars (e.g. fancy dashes are sometimes used instead of plain dash-minus, I guess caused by authoring in "fancy" word processors).

Seems best way to handle UTF-8 output, while still playing nice with users of non-utf8 locales, is to add this at the top of the command-line scripts:
```perl
use open ':locale';
```

I don't know, however, if that is supported as far back as 5.010001 now covered.

An alternative is to set binmode, but beware of its limitations as discussed at https://stackoverflow.com/questions/519309/how-do-i-read-utf-8-with-diamond-operator

**Comment by perlancar** [comment]
I believe `use open ':locale'` is available on 5.10.1.

I'm trying to add `use open ':locale'` or `use open ':utf8'` in my CLI framework Perinci::CmdLine::Lite. Could you tell me the command-line which you used to produce the Wide charcter warning?

**Comment by jonassmedegaard** [comment]
Quoting perlancar (2020-01-02 02:04:27)
> I believe `use open ':locale'` is available on 5.10.1.
> 
> I'm trying to add `use open ':locale'` or `use open ':utf8'` in my CLI framework Perinci::CmdLine::Lite. Could you tell me the command-line which you used to produce the Wide charcter warning?

get-regexp-pattern-pattern License::cc_by


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by perlancar** [comment]
utf8 flag added, will be in next release.
