### ISSUE TITLE
spews warning: Unknown PerlIO layer "locale"

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-App-RegexpPatternUtils#3]
When executing `show-regexp-pattern-module Example`, expected output is spewed to stdout, but additionally this is spewed to stderr:
> Unknown PerlIO layer "locale" at /home/jonas/perl5/lib/perl5/Perinci/CmdLine/Lite.pm line 427.

**Comment by perlancar** [comment]
It's a missing dependency to PerlIO::locale in Perinci-CmdLine-Lite. I've released new distros that remedy this.
